### ISSUE TITLE
PHP With NGINX - unix socket path

### ISSUE THREAD

**Issue by saxomoose** [fhsinchy/nginx-handbook-projects#2]
Thanks a lot for this introduction!

In the section "PHP With NGINX", I believe the line `fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;` should be replaced by `fastcgi_pass unix:/run/php/php7.4-fpm.sock;`. This provides the correct path to the unix socket.

**Comment by fhsinchy** [comment]
I'll have to take a look at that. I clearly remember checking the file path properly before putting it in the handbook but not sure if it has changed or anything. I'll look into it and get back to you. Thanks a lot for letting me know @saxomoose

**Comment by saxomoose** [comment]
My bad: your approach is also correct. The difference between /run and /var/run is a rabbit hole I don't want to dig into. 

You can safely close this.

**Comment by fhsinchy** [comment]
Okay dude @saxomoose
